export const FACULTIES = [
	{ faculty_id: 1, faculty_name: 'Forestry' },
	{ faculty_id: 2, faculty_name: 'Land and Food Systems' },
	{ faculty_id: 3, faculty_name: 'Education' },
	{ faculty_id: 4, faculty_name: 'Business' },
	{ faculty_id: 5, faculty_name: 'Arts' },
	{ faculty_id: 6, faculty_name: 'Applied Science' },
	{ faculty_id: 7, faculty_name: 'Science' },
	{ faculty_id: 8, faculty_name: 'Medicine' },
	{ faculty_id: 9, faculty_name: 'Other' },
	{ faculty_id: 10, faculty_name: 'Forestry' },
	{ faculty_id: 11, faculty_name: 'Land and Food Systems' },
	{ faculty_id: 12, faculty_name: 'Education' },
	{ faculty_id: 13, faculty_name: 'Business' },
	{ faculty_id: 14, faculty_name: 'Arts' },
	{ faculty_id: 15, faculty_name: 'Applied Science' },
	{ faculty_id: 16, faculty_name: 'Science' },
	{ faculty_id: 17, faculty_name: 'Medicine' },
	{ faculty_id: 18, faculty_name: 'Other' }
];

export const FACULTIES_V2 = {
	'1': 'Forestry',
	'2': 'Land and Food Systems',
	'3': 'Education',
	'4': 'Business',
	'5': 'Arts',
	'6': 'Applied Science',
	'7': 'Science',
	'8': 'Medicine',
	'9': 'Other',
	'10': 'Forestry',
	'11': 'Land and Food Systems',
	'12': 'Education',
	'13': 'Business',
	'14': 'Arts',
	'15': 'Applied Science',
	'16': 'Science',
	'17': 'Medicine',
	'18': 'Other'
};

export const PROGRAMS = [
	{ program_id: 1, program_name: 'Accounting' },
	{ program_id: 2, program_name: 'African Studies' },
	{ program_id: 3, program_name: 'American Studies' },
	{ program_id: 4, program_name: 'Anthropology' },
	{ program_id: 5, program_name: 'Archaeology' },
	{ program_id: 6, program_name: 'Art History' },
	{ program_id: 7, program_name: 'Asian Studies' },
	{ program_id: 8, program_name: 'Astronomy' },
	{ program_id: 9, program_name: 'Biochemistry' },
	{ program_id: 10, program_name: 'Biology' },
	{ program_id: 11, program_name: 'Biomedical Engineering' },
	{ program_id: 12, program_name: 'Business Administration' },
	{ program_id: 13, program_name: 'Canadian Studies' },
	{ program_id: 14, program_name: 'Chemistry' },
	{ program_id: 15, program_name: 'Chinese Studies' },
	{ program_id: 16, program_name: 'Civil Engineering' },
	{ program_id: 17, program_name: 'Classics' },
	{ program_id: 18, program_name: 'Cognitive Systems: Computational Intelligence and Design' },
	{ program_id: 19, program_name: 'Communication' },
	{ program_id: 20, program_name: 'Computer Science' },
	{ program_id: 21, program_name: 'Conservation and Restoration of Cultural Property' },
	{ program_id: 22, program_name: 'Criminology' },
	{ program_id: 23, program_name: 'Development Studies' },
	{ program_id: 24, program_name: 'Economics' },
	{ program_id: 25, program_name: 'Education' },
	{ program_id: 26, program_name: 'Electrical and Computer Engineering' },
	{ program_id: 27, program_name: 'English' },
	{ program_id: 28, program_name: 'Environmental Engineering' },
	{ program_id: 29, program_name: 'Environmental Sciences' },
	{ program_id: 30, program_name: 'European Studies' },
	{ program_id: 31, program_name: 'Film and Media Studies' },
	{ program_id: 32, program_name: 'Finance' },
	{ program_id: 33, program_name: 'French Studies' },
	{ program_id: 34, program_name: 'Geography' },
	{ program_id: 35, program_name: 'Germanic and Slavic Studies' },
	{ program_id: 36, program_name: 'Global Studies' },
	{ program_id: 37, program_name: 'History' },
	{ program_id: 38, program_name: 'Human Geography' },
	{ program_id: 39, program_name: 'Information Technology' },
	{ program_id: 40, program_name: 'International Business' },
	{ program_id: 41, program_name: 'International Relations' },
	{ program_id: 42, program_name: 'Italian Studies' },
	{ program_id: 43, program_name: 'Japanese Studies' },
	{ program_id: 44, program_name: 'Jewish Studies' },
	{ program_id: 45, program_name: 'Latin American Studies' },
	{ program_id: 46, program_name: 'Law' },
	{ program_id: 47, program_name: 'Linguistics' },
	{ program_id: 48, program_name: 'Management' },
	{ program_id: 49, program_name: 'Marketing' },
	{ program_id: 50, program_name: 'Mathematics' },
	{ program_id: 51, program_name: 'Mechanical Engineering' },
	{ program_id: 52, program_name: 'Media Studies' },
	{ program_id: 53, program_name: 'Microbiology' },
	{ program_id: 54, program_name: 'Middle Eastern Studies' },
	{ program_id: 55, program_name: 'Molecular Biology and Biochemistry' },
	{ program_id: 56, program_name: 'Music' },
	{ program_id: 57, program_name: 'Natural Resources Economics' },
	{ program_id: 58, program_name: 'Neuroscience' },
	{ program_id: 59, program_name: 'Nursing' },
	{ program_id: 60, program_name: 'Philosophy' },
	{ program_id: 61, program_name: 'Physics' },
	{ program_id: 62, program_name: 'Political Science' },
	{ program_id: 63, program_name: 'Psychology' },
	{ program_id: 64, program_name: 'Public Policy' },
	{ program_id: 65, program_name: 'Religious Studies' },
	{ program_id: 66, program_name: 'Romance Languages and Literatures' },
	{ program_id: 67, program_name: 'Russian and East European Studies' },
	{ program_id: 68, program_name: 'Science' },
	{ program_id: 69, program_name: 'Sociology' },
	{ program_id: 70, program_name: 'Spanish and Portuguese Studies' },
	{ program_id: 71, program_name: 'Statistics' },
	{ program_id: 72, program_name: 'Sustainability' },
	{ program_id: 73, program_name: 'Theatre' },
	{ program_id: 74, program_name: 'Urban Planning' },
	{ program_id: 75, program_name: "Women's and Gender Studies" }
];

export const PROGRAMS_V2 = {
	1: 'Accounting',
	2: 'African Studies',
	3: 'American Studies',
	4: 'Anthropology',
	5: 'Archaeology',
	6: 'Art History',
	7: 'Asian Studies',
	8: 'Astronomy',
	9: 'Biochemistry',
	10: 'Biology',
	11: 'Biomedical Engineering',
	12: 'Business Administration',
	13: 'Canadian Studies',
	14: 'Chemistry',
	15: 'Chinese Studies',
	16: 'Civil Engineering',
	17: 'Classics',
	18: 'Cognitive Systems: Computational Intelligence and Design',
	19: 'Communication',
	20: 'Computer Science',
	21: 'Conservation and Restoration of Cultural Property',
	22: 'Criminology',
	23: 'Development Studies',
	24: 'Economics',
	25: 'Education',
	26: 'Electrical and Computer Engineering',
	27: 'English',
	28: 'Environmental Engineering',
	29: 'Environmental Sciences',
	30: 'European Studies',
	31: 'Film and Media Studies',
	32: 'Finance',
	33: 'French Studies',
	34: 'Geography',
	35: 'Germanic and Slavic Studies',
	36: 'Global Studies',
	37: 'History',
	38: 'Human Geography',
	39: 'Information Technology',
	40: 'International Business',
	41: 'International Relations',
	42: 'Italian Studies',
	43: 'Japanese Studies',
	44: 'Jewish Studies',
	45: 'Latin American Studies',
	46: 'Law',
	47: 'Linguistics',
	48: 'Management',
	49: 'Marketing',
	50: 'Mathematics',
	51: 'Mechanical Engineering',
	52: 'Media Studies',
	53: 'Microbiology',
	54: 'Middle Eastern Studies',
	55: 'Molecular Biology and Biochemistry',
	56: 'Music',
	57: 'Natural Resources Economics',
	58: 'Neuroscience',
	59: 'Nursing',
	60: 'Philosophy',
	61: 'Physics',
	62: 'Political Science',
	63: 'Psychology',
	64: 'Public Policy',
	65: 'Religious Studies',
	66: 'Romance Languages and Literatures',
	67: 'Russian and East European Studies',
	68: 'Science',
	69: 'Sociology',
	70: 'Spanish and Portuguese Studies',
	71: 'Statistics',
	72: 'Sustainability',
	73: 'Theatre',
	74: 'Urban Planning',
	75: "Women's and Gender Studies"
};

export const STANDINGS = [
	{ standing_id: 1, standing_name: 'First Year' },
	{ standing_id: 2, standing_name: 'Second Year' },
	{ standing_id: 3, standing_name: 'Third Year' },
	{ standing_id: 4, standing_name: 'Fourth Year' },
	{ standing_id: 5, standing_name: 'Fifth Year and up' },
	{ standing_id: 6, standing_name: 'Graduate Student' },
	{ standing_id: 7, standing_name: 'Alumni' },
	{ standing_id: 8, standing_name: 'Other' }
];

export const STANDINGS_V2 = {
	1: 'First Year',
	2: 'Second Year',
	3: 'Third Year',
	4: 'Fourth Year',
	5: 'Fifth Year and up',
	6: 'Graduate Student',
	7: 'Alumni',
	8: 'Other'
};

export const SOCIALS = {
	'1': {
		id: 1,
		name: 'GitHub',
		domain: 'github.com'
	},
	'2': {
		id: 2,
		name: 'Facebook',
		domain: 'facebook.com'
	},
	'3': {
		id: 3,
		name: 'Instagram',
		domain: 'instagram.com'
	},
	'4': {
		id: 4,
		name: 'LinkedIn',
		domain: 'linkedin.com'
	},
	'5': {
		id: 5,
		name: 'Twitter',
		domain: 'twitter.com'
	},
	'6': {
		id: 6,
		name: 'Website',
		domain: null
	},
	'7': {
		id: 7,
		name: 'Figma',
		domain: 'figma.com'
	},
	'8': {
		id: 8,
		name: 'Other',
		domain: null
	}
};
